### ISSUE TITLE
SystemRequirements is malformed

### ISSUE THREAD

**Issue by frafra** [ropensci/NLMR#104]
Hi,
I am not able to install this library, as R is complaining that `SystemRequirements` is malformed.

```r
#10 2.641 Error in read.dcf(path) : Line starting 'SystemRequir ...' is malformed!
```

I am installing a package which has NLMR as a dependency, using Ubuntu 22.04.
This seems to happen with NLMR only, and only when using the `github::` prefix (the default one), while it works with `url::`.

This works:
```
Rscript -e "devtools::install_url('https://github.com/ropensci/NLMR/archive/refs/heads/master.zip')"
```

This fails:
```
Rscript -e "devtools::install_github('ropensci/NLMR')"
```

Output:
```
Error: Failed to install 'unknown package' from GitHub:
  Line starting 'SystemRequir ...' is malformed!
Execution halted
```

**Comment by mhesselbarth** [comment]
Hey, 

I can't reproduce the error on macOS, so not sure what is happening on your machine.

**Comment by frafra** [comment]
This seems a locale issue. Setting the locale to `en_US.UTF-8` fixes the issue. Leaving the default `C` makes it fail. It seems triggered with this repo only. It could be that some unicode characters used in `DESCRIPTION` are not handled correctly by devtools.
