### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by csim063** [ropensci/NLMR#32]

**Comment by marcosci** [comment]
nlm_mosaicfield:

In addition, so more information about how these work, and when you would use them would be useful.

**Comment by csim063** [comment]
ping @marcosci 

More verbose, that is not normally a good thing. Do you mean more detailed? I agree we should link the paper

**Comment by marcosci** [comment]
Po-tay-to po-tah-to, my plan would be to streamline the code quite a lot in the next weeks and change some underlying parts and in this process also update the documentation/vignettes (more details, our paper, the background vignette and so on).

I tackle part 1, you tackle part 2? :weight_lifting_man:

**Comment by csim063** [comment]
Po-tay-to ham-burger. Ok plan sounds good, I may make that an aim for Edersee

**Comment by marcosci** [comment]
Sweet :)
