### ISSUE TITLE
nlm_gaussianfield()

### ISSUE THREAD

**Issue by Z3tt** [ropensci/NLMR#34]
General pattern changes when increasing the range of autocorrelation:

``` r
library(NLMR)
#> Warning: Paket 'NLMR' wurde unter R Version 3.4.3 erstellt

gfs <- as.list(20)

suppressWarnings(
  for (i in 1:20) {
    set.seed(1)
    gfs[i] <- nlm_gaussianfield(ncol = 50, nrow = 50, mag_var = 3, nug = 0.01, autocorr_range = i)
  }
)

util_facetplot(gfs)
```

![](https://i.imgur.com/gsgPQP2.png)

Created on 2018-03-16 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

One would expect the same general pattern with increasing clustering (as one would decrease the resolution) but the pattern changes (i.e. same pattern for facets 1:8, 9:14, 15:20). Not sure if this is a bug or what we expect the algorithm to do - for me it seems unlogical.

(Edit: I used the CRAN version of NLMR to easily plot the facet of all nlms, but the outcome is exactly the same with the dev version.)

**Comment by marcosci** [comment]
going to change gaussianfield anyways, so I hope that is fixed in 0.4
