### ISSUE TITLE
NLMR mentioned in review -> add to publication list?

### ISSUE THREAD

**Issue by bitbacchus** [ropensci/NLMR#58]
Langhammer, Maria, Jule Thober, Martin Lange, Karin Frank, and Volker Grimm. “Agricultural Landscape Generators for Simulation Models: A Review of Existing Solutions and an Outline of Future Directions.” Ecological Modelling 393 (February 2019): 135–51. https://doi.org/10.1016/j.ecolmodel.2018.12.010.

They briefly mention NLMR. Should we add it to our list? Or just if s/o actually uses the package?

**Comment by marcosci** [comment]
Done, also now in a new book chapter:

Fletcher R., Fortin MJ. (2018) Land-Cover Pattern and Change. In: Spatial Ecology and Conservation Modeling. Springer, Cham
