### ISSUE TITLE
Keep NEWS up to date

### ISSUE THREAD

**Issue by sckott** [ropensci/NLMR#59]
Just noticed that your NEWS/NEWS.md file doesn't have any release notes for the recent CRAN release. Please make sure your NEWS/NEWS.md has release notes for every version released to CRAN.  See https://ropensci.github.io/dev_guide/releasing.html#news for more

**Comment by marcosci** [comment]
Oops, that went under my radar, fixed (https://github.com/ropensci/NLMR/commit/8936a2342ccb4e8110dd3d0441523fd550c01ecc)
