### ISSUE TITLE
Makevars flags do not work

### ISSUE THREAD

**Issue by JohannesOberpriller** [ropensci/NLMR#61]
Hi Marco, 

I just have seen, that the makevars does not work. One can not overwrite the CXX_STD compiler, but you can overwrite the one which builds the package by PKG_CXX_STD. However, the 11 standard is already the default compiler, but if you plan to change to another standard, the above flag will make it compile. 

Cheers, Johannes

**Comment by marcosci** [comment]
Hi Johannes,

are you sure? Seems to work on every machine so far and the R Manual says the exact same thing:

https://cran.r-project.org/doc/manuals/r-release/R-exts.html#Using-C_002b_002b11-code

Cheers,
Marco

**Comment by JohannesOberpriller** [comment]
Hi Marco, 

As I understand the concept and R manual, there are two makevars files important for the build of a package. The first is in in your library folder and sets the standard options. The second one, which is directly contained in the package can overwrite the standard-options. So far this has worked for me. 

https://cran.r-project.org/doc/manuals/r-release/R-exts.html#Using-Makevars

Cheers, 
Johannes

**Comment by marcosci** [comment]
done
