### ISSUE TITLE
For adding to publication record

### ISSUE THREAD

**Issue by laurajanegraham** [ropensci/NLMR#64]
We use NLMR to generate landscapes for the simulation section of Graham, LJ, Spake, R, Gillings, S, Watts, K, Eigenbrod, F. Incorporating fine‐scale environmental heterogeneity into broad‐extent models. Methods Ecol Evol. 2019; 10: 767– 778. https://doi.org/10.1111/2041-210X.13177

**Comment by marcosci** [comment]
See Cedrics Issue :) Doing that next week!
