### ISSUE TITLE
nlmr package removed from CRAN

### ISSUE THREAD

**Issue by tdokhelar** [ropensci/NLMR#75]
Hello,

When I tried to install the nlmr package, I discovered that it had been removed from CRAN.

Having a lot of trouble to install the package from the source file, I would like to know if someone has a solution to propose me to install it on Rstudio !

Best,

**Comment by bitbacchus** [comment]
Sorry for the trouble, we're on CRAN again soon...

In the meantime, just install the `remotes` package and then type

```
remotes::install_github("ropensci/NLMR")
```

in your R Console.

**Comment by mhesselbarth** [comment]
Just saw it was archived again on  2021-03-16. The `master` branch version seems to be fixed though. Just needs to be updated on CRAN I think

**Comment by srfall** [comment]
Any progress on this?
In the current state one can't put NLMR into the dependencies of other packages as R-CMD-check fails then.

**Comment by bitbacchus** [comment]
Uh, yes. This sucks. I'll talk to @marcosci tomorrow and see if I can help with this.

**Comment by mhesselbarth** [comment]
I think still the master branch is fixed already - it just needs to be uploaded to CRAN.

**Comment by marcosci** [comment]
Yeah, it was fixed but the declined putting it on CRAN because of lacking documentation.

Resubmitted it last week and they just confirmed that it's now (without changing anything on the docs ...) on it’s way to CRAN
