### ISSUE TITLE
Pre-build vignette

### ISSUE THREAD

**Issue by maelle** [ropensci/NLMR#91]
The docs building was cancelled because it went over 60 minutes https://github.com/r-universe/ropensci/runs/4938412185?check_suite_focus=true

It might make sense to pre-compute vignettes cf https://ropensci.org/blog/2019/12/08/precompute-vignettes/

**Comment by maelle** [comment]
:wave: @marcosci :smile_cat:

**Comment by marcosci** [comment]
Implemented :)
